CREATE TABLE mdm.Staff
(
StaffID INT NOT NULL IDENTITY(1,1),
PayrollID INT NOT NULL,
FirstName VARCHAR(250) NULL,
LastName VARCHAR(250) NULL,
[Address] VARCHAR(250) NULL,
City VARCHAR(250) NULL,
[State] VARCHAR(100) NULL,
Zip VARCHAR(20) NULL

CONSTRAINT staff_id PRIMARY KEY (StaffID)
);